//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicBeePlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicBeePlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///* Skeleton V1.2
        ///* Copyright 2011, Dave Gamache
        ///* www.getskeleton.com
        ///* Free to use under the MIT license.
        ///* http://www.opensource.org/licenses/mit-license.php
        ///* 6/20/2012
        ///*/
        ///
        ///
        ////* Table of Content
        ///==================================================
        ///	#Reset &amp; Basics
        ///	#Basic Styles
        ///	#Site Styles
        ///	#Typography
        ///	#Links
        ///	#Lists
        ///	#Images
        ///	#Buttons
        ///	#Forms
        ///	#Misc */
        ///
        ///
        ////* #Reset &amp; Basics (Inspired by E. Meyers)
        ///================================================== */
        ///	html, body, div, span, applet, object, iframe, h1, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _base {
            get {
                return ResourceManager.GetString("_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon beekeeper {
            get {
                object obj = ResourceManager.GetObject("beekeeper", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;!--[if lt IE 7 ]&gt;&lt;html class=&quot;ie ie6&quot; lang=&quot;en&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 7 ]&gt;&lt;html class=&quot;ie ie7&quot; lang=&quot;en&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 8 ]&gt;&lt;html class=&quot;ie ie8&quot; lang=&quot;en&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if (gte IE 9)|!(IE)]&gt;&lt;!--&gt;&lt;html lang=&quot;en&quot;&gt; &lt;!--&lt;![endif]--&gt;
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot;&gt;
        ///  &lt;title&gt;Beekeeper&lt;/title&gt;
        ///  &lt;meta name=&quot;description&quot; content=&quot;Beekeeper basic info, landing page&quot;&gt;
        ///  &lt;meta name=&quot;author&quot; content=&quot;grismar@grismar.net&quot;&gt;
        ///
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///* Skeleton V1.2
        ///* Copyright 2011, Dave Gamache
        ///* www.getskeleton.com
        ///* Free to use under the MIT license.
        ///* http://www.opensource.org/licenses/mit-license.php
        ///* 6/20/2012
        ///*/
        ///
        ////* Table of Content
        ///==================================================
        ///	#Site Styles
        ///	#Page Styles
        ///	#Media Queries
        ///	#Font-Face */
        ///
        ////* #Site Styles
        ///================================================== */
        ///
        ////* #Page Styles
        ///================================================== */
        ///
        ////* #Media Queries
        ///=========================================== [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string layout {
            get {
                return ResourceManager.GetString("layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///* Skeleton V1.2
        ///* Copyright 2011, Dave Gamache
        ///* www.getskeleton.com
        ///* Free to use under the MIT license.
        ///* http://www.opensource.org/licenses/mit-license.php
        ///* 6/20/2012
        ///*/
        ///
        ///
        ////* Table of Contents
        ///==================================================
        ///    #Base 960 Grid
        ///    #Tablet (Portrait)
        ///    #Mobile (Portrait)
        ///    #Mobile (Landscape)
        ///    #Clearing */
        ///
        ///
        ///
        ////* #Base 960 Grid
        ///================================================== */
        ///
        ///    .container                                  { position: relative; width: 96 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string skeleton {
            get {
                return ResourceManager.GetString("skeleton", resourceCulture);
            }
        }
    }
}
